# Book settings
title                       : "雑記 備忘録"
author                      : "柴田 侃汰 (Twitter: @shibata12k)"
copyright                   : "2021-2022"

# Execution settings
execute:
  execute_notebooks         : off

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath

# HTML-specific settings
html:
  google_analytics_id       : "G-KLZ68TSGC7"

# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab
  binderhub_url             : ""