title: "備忘録 雑記"
author: "柴田 侃汰(@shibata12k)"

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath