# Book settings
title                       : "備忘録 雑記"
author                      : "柴田 侃汰 (Twitter: @shibata12k)"
copyright                   : "2021-2022"

# Execution settings
execute:
  execute_notebooks         : off

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath

# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab
  binderhub_url             : ""